name: build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: init
        run: |
          # upx 3.95 for mips wait for 4.0 fix https://github.com/upx/upx/issues/342
          sudo apt-get update
          sudo apt-get install -y upx
          sudo rm -rf /usr/bin/go*
          sudo rm -rf /usr/local/go
          wget https://dl.google.com/go/go1.16.2.linux-amd64.tar.gz -O go.tar.gz
          sudo tar -C /usr/local -xzf go.tar.gz
          wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
          tar xf upx-3.96-amd64_linux.tar.xz
          mv upx-3.96-amd64_linux/upx .
          rm -rf upx-3.96-amd64_linux*
      - name: build
        run: |
          mkdir tmp
          mkdir bin
          # Do not use "--depth=1" due to tags
          git clone -b fix/udp-sniffing https://github.com/XTLS/Xray-core.git
          cd Xray-core
          git checkout tags/v1.4.2
          cd ..
          wget https://raw.githubusercontent.com/felix-fly/xray-openwrt/master/build.sh
          chmod +x ./build.sh
          ./build.sh android arm64
          ./build.sh darwin amd64
          ./build.sh linux 386
          ./build.sh linux amd64
          ./build.sh linux armv5
          ./build.sh linux armv6
          ./build.sh linux armv7
          ./build.sh linux arm64
          ./build.sh linux mips
          ./build.sh linux mipsle
          ./build.sh linux mips64
          ./build.sh linux mips64le
      - name: Upload artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.UPLOAD_KEY }}"
          prerelease: false
          files: |
            bin/*.tar.gz
